version: '2'
services:
  messaging-app-db:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: adam
      MYSQL_PASSWORD: password
