name: messaging_app_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  jwt_decoder: ^1.0.1
  date_format: ^1.0.9
  awesome_dialog: ^1.2.0
  adaptive_dialog: ^0.7.5+3
  modal_progress_hud: ^0.1.3
  file_picker: ^2.0.6
  dio: ^3.0.10
  signalr_client: ^0.1.6
  flutter_secure_storage: ^3.3.5
  get_it: ^5.0.3
  injectable: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/